module.exports = {
  INVOICE_CREATED: 'INVOICE_CREATED',
  PAY_ORDER_UPDATED: 'PAY_ORDER_UPDATED',
  RECEIPT_CREATED: 'RECEIPT_CREATED',
  CREDIT_NOTE_CREATED: 'CREDIT_NOTE_CREATED',
  DEBIT_NOTE_CREATED: 'DEBIT_NOTE_CREATED',
  CLOSED: 'CLOSED',
};